version: '3.8'

services:
  app:
    build: .
    container_name: mini-erp-app
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - mysql
      - redis
    networks:
      - mini-erp-network

  web:
    image: nginx:alpine
    container_name: mini-erp-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - mini-erp-network

  mysql:
    image: mysql:8
    container_name: mini-erp-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mini_erp
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    networks:
      - mini-erp-network
    volumes:
      - dbdata:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: mini-erp-redis
    restart: unless-stopped
    networks:
      - mini-erp-network

  mailpit:
    image: axllent/mailpit
    container_name: mini-erp-mailpit
    restart: unless-stopped
    ports:
      - "8025:8025"
    networks:
      - mini-erp-network

networks:
  mini-erp-network:
    driver: bridge
volumes:
  dbdata:
